spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expert
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

jwt:
  secret:
    key: mySecretKeymySecretKeymySecretKey123456retKeymySecretKey123456